#ifndef __QL_EVENT_H__
#define __QL_EVENT_H__

#ifdef __cplusplus
extern "C"{
#endif /* __cplusplus */

#include "qosa_def.h"
#include "qosa_system.h"

#define QL_MAX_MSG_COUNT            (16)
#define QL_EVENT_INVALID            0x0000


typedef enum
{
	QL_EVENT_MAIN_STATE                 = 0x1000,

	QL_EVENT_MODULE_INIT                = 0x2000,
	QL_EVENT_MODULE_FAILURE,
	QL_EVENT_SIM_START,
	QL_EVENT_SIM_READY_FAILURE,
	QL_EVENT_NW_START,
	QL_EVENT_NET_NET_REG_SUCCESS,
	QL_EVENT_NET_NET_REG_FAILURE,
	QL_EVENT_DATACALL_START,
	QL_EVENT_NET_DATACALL_SUCCESS,
	QL_EVENT_NET_DATACALL_FAILURE,
	QL_EVENT_NET_KEEPALIVE,

	QL_EVENT_SOCKET_INIT_SUCCESS        = 0x3000,
	QL_EVENT_SOCKET_CONNECT_SUCCESS,
	QL_EVENT_SOCKET_CONNECT_FAILURE,
	QL_EVENT_SOCKET_SEND_DATA_SUCCESS,
	QL_EVENT_SOCKET_SEND_DATA_FAILURE,
	QL_EVENT_SOCKET_RECV_DATA_SUCCESS,
	QL_EVENT_SOCKET_RECV_DATA_FAILURE,

	QL_EVENT_FTP_INIT_SUCCESS           = 0x4000,
	QL_EVENT_FTP_CONNENT_SUCCESS,
	QL_EVENT_FTP_UP_SUCCESS,
	QL_EVENT_FTP_UP_FAIL,
	QL_EVENT_FTP_GET_SUCCESS,
	QL_EVENT_FTP_GET_FAIL,
	QL_EVENT_FTP_CLOSE_SUCCESS,

	QL_EVENT_HTTP_INIT_SUCCESS          = 0x5000,
	QL_EVENT_HTTP_REQUEST,
	QL_EVENT_HTTP_REQUEST_SUCCESS,
	QL_EVENT_HTTP_REQUEST_FAILURE,
} QL_EVENT;


typedef struct
{
	QL_EVENT event;
	s32_t arg1;
	s32_t arg2;
	s32_t arg3;
} ql_msg, *ql_msg_t;


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* __QL_EVENT_H__ */
